### ISSUE TITLE
Import AdmitadSDK via cocoa pods

### ISSUE THREAD

**Issue by igorkazakov** [AdmitadSDK/ios_sdk#2]
Import AdmitadSDK to objective с project or swift 3.2 project I have the same errors
![2018-03-01 10 20 08](https://user-images.githubusercontent.com/8243056/36831852-2dcf65b6-1d3a-11e8-990f-c53d9d5a1d7f.png)
Xcode 9.2

**Comment by igorkazakov** [comment]
You forgot to change swift version in build settings AdmitadSdk from 3.2 to 4.0

**Comment by ksajxai** [comment]
project file of AdmitadSDK is in the repo and swift version has always been set to 4.0

Please, check your local settings
